apiVersion: v1
kind: Service
metadata:
  name: anchor-domain-service-svc
  labels:
    app: anchor-domain-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: anchor-domain-service